version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_dbx
    restart: always
    environment:
      MYSQL_DATABASE: softxpert
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
